### ISSUE TITLE
Add the ports 14 and 15

### ISSUE THREAD

**Issue by vtec83** [ioBroker/ioBroker.megad#2]

**Comment by GermanBluefox** [comment]
It is there:
https://github.com/ioBroker/ioBroker.megad/commit/926b09bca2ff1cd5f115b7b6725f092b944224cd

Can you test it?

Write in /opt/iobroker 
```npm install https://github.com/ioBroker/ioBroker.megad/tarball/master```
And may be install the adpater anew.

**Comment by vtec83** [comment]
Ok
