### ISSUE TITLE
When starting the driver, not found objects.

### ISSUE THREAD

**Issue by vtec83** [ioBroker/ioBroker.megad#3]
Log:
megad-0	2015-06-20 14:05:36	error	Unknown port ID ports.port15_double
megad-0	2015-06-20 14:05:36	error	Unknown port ID ports.port15_long
...........
megad-0	2015-06-20 14:05:36	error	Unknown port ID ports.port2_double
megad-0	2015-06-20 14:05:36	error	Unknown port ID ports.port2_long
megad-0	2015-06-20 14:05:36	warn	Unknown port undefined
megad-0	2015-06-20 14:05:36	warn	Unknown port undefined
megad-0	2015-06-20 14:05:36	warn	Unknown port undefined
megad-0	2015-06-20 14:05:36	info	try to control ports.port2 with false
megad-0	2015-06-20 14:05:36	error	Unknown port ID ports.port1_double
megad-0	2015-06-20 14:05:36	error	Unknown port ID ports.port1_long
megad-0	2015-06-20 14:05:36	info	try to control ports.port1 with false
megad-0	2015-06-20 14:05:36	error	Unknown port ID ports.port0_double
megad-0	2015-06-20 14:05:36	error	Unknown port ID ports.port0_long

And 14,15 ports cannot be: double or long. Because these ports ADC.

**Comment by GermanBluefox** [comment]
It should function now. Can you check it?
