### ISSUE TITLE
When you make any changes to the driver setting and all the objects (ports.port*_long and  ports.port*_double) are deleted automatically

### ISSUE THREAD

**Issue by vtec83** [ioBroker/ioBroker.megad#4]
Log:

megad-0	2015-06-20 14:18:19	warn	Unknown port undefined
megad-0	2015-06-20 14:18:19	warn	Unknown port undefined
megad-0	2015-06-20 14:18:19	warn	Unknown port undefined
megad-0	2015-06-20 14:18:19	warn	Unknown port undefined
megad-0	2015-06-20 14:18:19	warn	Unknown port undefined
megad-0	2015-06-20 14:18:19	warn	Unknown port undefined
megad-0	2015-06-20 14:18:19	warn	Unknown port undefined
megad-0	2015-06-20 14:18:19	warn	Unknown port undefined
megad-0	2015-06-20 14:18:19	warn	Unknown port undefined
megad-0	2015-06-20 14:18:19	warn	Unknown port undefined
megad-0	2015-06-20 14:18:19	warn	Unknown port undefined
megad-0	2015-06-20 14:18:19	warn	Unknown port undefined
megad-0	2015-06-20 14:18:19	info	try to control ports.port15 with false
megad-0	2015-06-20 14:18:19	info	try to control ports.port14 with false
megad-0	2015-06-20 14:18:19	info	try to control ports.port13 with false
megad-0	2015-06-20 14:18:19	info	try to control ports.port12 with false
megad-0	2015-06-20 14:18:19	info	try to control ports.port11 with false
megad-0	2015-06-20 14:18:19	info	try to control ports.port10 with false
megad-0	2015-06-20 14:18:19	info	try to control ports.port9 with false
megad-0	2015-06-20 14:18:19	info	try to control ports.port8 with false
megad-0	2015-06-20 14:18:19	info	try to control ports.port7 with false
megad-0	2015-06-20 14:18:19	info	try to control ports.port6 with false
megad-0	2015-06-20 14:18:19	info	try to control ports.port5 with false
megad-0	2015-06-20 14:18:19	info	try to control ports.port4 with false
megad-0	2015-06-20 14:18:19	warn	Unknown port undefined
megad-0	2015-06-20 14:18:19	warn	Unknown port undefined
megad-0	2015-06-20 14:18:19	warn	Unknown port undefined
megad-0	2015-06-20 14:18:19	warn	Unknown port undefined
megad-0	2015-06-20 14:18:18	info	try to control ports.port3 with false
megad-0	2015-06-20 14:18:18	info	try to control ports.port2 with false
megad-0	2015-06-20 14:18:18	info	try to control ports.port1 with false
megad-0	2015-06-20 14:18:18	error	Unknown port ID ports.port0_double
megad-0	2015-06-20 14:18:18	error	Unknown port ID ports.port0_long
megad-0	2015-06-20 14:18:18	info	try to control ports.port0 with false
megad-0	2015-06-20 14:18:17	info	http server listening on port 80
megad-0	2015-06-20 14:18:17	info	starting. Version 0.1.1 in /opt/iobroker/node_modules/iobroker.megad
host-cubieboard2	2015-06-20 14:18:15	info	instance system.adapter.megad.0 started with pid 4916
host-cubieboard2	2015-06-20 14:18:13	info	instance system.adapter.megad.0 terminated with code 0 (OK)
host-cubieboard2	2015-06-20 14:18:13	info	stopInstance system.adapter.megad.0 killing pid 4878
host-cubieboard2	2015-06-20 14:18:13	info	stopInstance system.adapter.megad.0

**Comment by GermanBluefox** [comment]
Please check and close.
